### ISSUE TITLE
Sub palette - Please turn on Javascript in your browser.

### ISSUE THREAD

**Issue by xApep** [terminal42/contao-tablelookupwizard#10]
Hi.
If you use subpalettes and if the subpalettes has tableLookup than you get and error: Please turn on Javascript in your browser.

Flow:
You click checkbox let say Add consultant. Than the tableLookup field is showen but you can't use search because there is an error: Please turn on Javascript in your browser.

If you don't use tableLookup as subpallet than it works fine.

I'm using Contao 3.5.6 and latest git version for tablelookupwizard extension.

**Comment by qzminski** [comment]
I guess the wizard has to be also initialized on the ```ajax_change``` event. There was pretty the same issue with tinyMCE and other JS scripts in subpalettes in the past.

**Comment by EDsolution** [comment]
Thanks Kamil for detail explanation.

Is there any other news about fixing this from devs?

Thanks.

**Comment by qzminski** [comment]
@aschempp @Toflar

**Comment by Toflar** [comment]
Feel free to contribute.

**Comment by qzminski** [comment]
Implemented in 250062b.
