### ISSUE TITLE
More features for Foreign tables :D

### ISSUE THREAD

**Issue by webexmachina** [terminal42/contao-tablelookupwizard#13]
Hi,

More a feature to add than an issue :)
For a project, I had to manage a big database, With the TableLookupWizard, it was easy to connect simple jointures.
But at one time, I had to use an associative table and I was stuck by the Joins array who didn't let me write more than the columns for the Join On structure.

For my problem, I find a dirty way to do it (but it's for me, with my rules soooo...), by overriding "prepareJoins" function and add a if statement who check if there is a "." in my jkey and fkey.
If it's the case, I don't use the prefixes but I let my code tell what to do. If not, your code does the job.

```
foreach ($this->arrJoins as $k => $v)
            {
                if(strpos($v['jkey'], ".") != false && strpos($v['fkey'], ".") != false)
                {
                    $this->arrQueryProcedure[] = sprintf("%s %s ON %s = %s", $v['type'], $k, $v['jkey'], $v['fkey']);
                }
                else
                {
                    $this->arrQueryProcedure[] = sprintf("%s %s ON %s.%s = %s.%s", $v['type'], $k, $k, $v['jkey'], $this->foreignTable, $v['fkey']);
                }
            }
```

Maybe you should add this way to use the Wizard, not in my way because it's crap, but with your vision :)

Best regards,
Julien, from Web ex Machina

**Comment by qzminski** [comment]
I think we should just rewrite this extension one day to be more flexible. Then you would simple create your own widget extending this one and everything would be a piece of cake 😉  Hardcoding that particular case (or any other) is not the way to go imo.

**Comment by aschempp** [comment]
Or just use the new picker ;-)

**Comment by webexmachina** [comment]
As I say, it's not an issue, and I'm aware hardcoding is not a good way but when it's jut for me, I can be less careful ;)

@aschempp The new picker you said ?

**Comment by aschempp** [comment]
Contao 4.4 provides a new picker that allows to pick any record from the Contao backend. The Contao backend already provides all the search functionality etc. Might be a replacement for a lot of cases, but certainly not all.

**Comment by webexmachina** [comment]
Okay ! I'll try it :)
Thanks for your answers and see you later !
