### ISSUE TITLE
Create a short documentation

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-tablelookupwizard#7]

**Comment by aschempp** [comment]
^^

**Comment by qzminski** [comment]
It's already in develop branch so I suggest that you merge it and release a new version.

**Comment by aschempp** [comment]
I just checked that, @Toflar rewrite the script in January 2014 (*sigh*). I guess we should release version 3, but I don't know if it does support Contao 3.2? It uses custom templates, but as far as I remember the changes in Contao 3.3 were for frontend widgets?

**Comment by Toflar** [comment]
Yeah, I rewrote that completely. Wasn't it released as 2.0?

**Comment by aschempp** [comment]
Apparently not, it's still in develop ;-)

**Comment by Toflar** [comment]
I've just released version 3.0. Check the changelog file if you want to know what's new :D
